#!/usr/bin/env node
/* Pieter Colpaert */

/**
 * This script reads a zipped GTFS archive and maps it into RDF (text/turtle) in a streaming fashion
 */

var fs = require('fs');
var N3 = require('n3');
var N3Util = N3.util;
var Mapper = require('./lib/gtfs-csv2connections.js');
var die = function (msg) {
  console.log(msg);
  process.exit();
}

//check whether the location of the zip has been set and zip exists
var path = "",
    version = "",
    baseuri = "";
if (process.argv[2]) {
  path = process.argv[2];
}else {
  die("Give a path towards your gtfs feed as a first argument");
}

if (!fs.existsSync(path)) {
  die(path + " not found");
}

//get the feedname: the name of the zip file
if (/(.*\/)?(.*?)\.zip/.exec(path)) {
  var feedname = /(.*\/)?(.*?)\.zip/.exec(path)[2];
} else {
  die ("Not a zipfile: " + path);
}

var mapper = new Mapper({feedname: feedname});
mapper.promiseConnectionsStream(fs.createReadStream(path)).then(function (stream) {
  stream.on("data", function (data) {
    console.log(data);
  }).on("error", function (error) {
    console.error(error);
  });
});
